route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1h
  routes:
    - match:
        alertname: "HighCPUUsageVM1"
      receiver: 'shutdown_vm1'
    - match:
        alertname: "InstanceDown"
      receiver: 'webhook_receiver'

receivers:
  - name: 'webhook_receiver'
    webhook_configs:
      - url: 'http://192.168.119.133:5001/'  # Webhook endpoint on VM2

  - name: 'shutdown_vm1'
    webhook_configs:
      - url: 'http://192.168.119.131:5001/'  # Webhook endpoint on VM1
