global:
scrape_interval: 15s
14
evaluation_interval: 15s
alerting:
alertmanagers:
- static_configs:
- targets:
scrape_configs:
- job_name: 'prometheus'
scrape_interval: 5s
scrape_timeout: 5s
static_configs:
- targets: ['localhost:9090']
- job_name: 'node_exporter_vm1'
static_configs:
- targets: ['192.168.119.131:9100']
- job_name: 'node_exporter_vm2'
static_configs:
- targets: ['192.168.119.133:9100']
- job_name: 'keepalived'
static_configs:
- targets: ['192.168.119.140:9100']
alerting:
alertmanagers:
- static_configs:
- targets: ['localhost:9093']
rule_files:
- "/etc/prometheus/alert.rules"
